apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ligera
  namespace: default
spec:
  # Borramos la línea de replicas, porque ahora el HPA mandará sobre este número
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:      # Lo que el pod reserva para empezar
            memory: "32Mi"
            cpu: "50m"
          limits:        # El techo máximo que no puede pasar
            memory: "64Mi"
            cpu: "100m"
