apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        # Activación de las estadísticas internas de Nginx
        location /stub_status {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            deny all;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-ligera
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        # Crucial para que Prometheus encuentre este Pod automáticamente
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      # CONTENEDOR 1: Nginx (Tu App)
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"

      # CONTENEDOR 2: Exporter (El "espía" de métricas)
      - name: exporter
        image: nginx/nginx-prometheus-exporter:latest
        args:
          - -nginx.scrape-uri=http://localhost/stub_status
        ports:
        - containerPort: 9113
        resources:
          limits:
            cpu: "20m"
            memory: "32Mi"

      volumes:
      - name: config-volume
        configMap:
          name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: app-ligera
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: metrics
    port: 9113
    targetPort: 9113
  selector:
    app: web