---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mi-llave-bitcoin
  namespace: default
spec:
  encryptedData:
    api-key: AgDNNf/aJPCRMOabf4vttQHEIfF4xtnyhH9GavaiKgU0+PL0ZptedI7iGgaNhjtmsPf6EBuHuBOWBwyUE8qlb7GccbqMC+Tf2kKLWszhdBi9xiH7F8TxAK4tLB3SEayhgsq1yy+TenDiWoTTbCIN1m7GlC6WRrapo1gS315ou9qxhN+atuWxoe/ZnLTvKT/oDcwbAZauKqlLrklxHpxyWvyUPGGBhwo76lWjfTKWY/80GwKupAfT0f/NChucuHRXr9wQMIV1sCWx2tZYcwDgQFCLvoVsNemcuqKL9zWpPWBBFf3OdYF5jbapN33sMk+44STVREKay7Tm6lL5p27Yygg0OJapCILnti3h5RXWjttAKO0VCbMJZDGRHQ3m+aEVQdk/kSoNaOflvNARVu9YoiQMeLuGHMF/wtobdV3sqVyZieQzxvEvHugsqHxrzYg7r7WjuNaw2beLsy6Fidj3KUOlpui/+Lk1MI+janTADcoij6wdn5lJY4hb9/GVBHuUEQLYlQZMpxS2a5HG1q1WKMJbNuaB+zXM2KMiOcpZ5G8wkmXj8X3kqkvBnxxmbkpBHyGkDUgheXlXSQ6Cq9GK6Rpd8EIdjp2nBma+49Y9ufCTxZ5tJIichEeujXWU2iTifxgKoUBkT47To0WkkOd69eLtRm2ud4UMIkaY9JMzD74lWkZrLtexKK6CTkm2hag3OBHgeUcAqK+ViY241ZLIX4/eKgJuZA==
  template:
    metadata:
      creationTimestamp: null
      name: mi-llave-bitcoin
      namespace: default
